#!/bin/sh
# devtmpfs does not get automounted for initramfs
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys
/bin/mount -t devtmpfs devtmpfs /dev
/sbin/mdev -s
mkdir -p /dev/pts
mount -vt devpts -o gid=4,mode=620 none /dev/pts
chmod 666 /dev/ptmx


echo "STT{REAL_FLAG_ON_THE_SERVER}" >> /flag.txt
chmod 400 /flag.txt


insmod /root/stt.ko
mknod /dev/STT c 248 0

echo -e "\nBoot took $(cut -d ' ' -f1 /proc/uptime) seconds\n"

setsid /bin/cttyhack setuidgid 1000 /bin/sh

umount /proc
umount /sys
poweroff -d 0 -f
